version: '2'
services:
  db:
    image: "robertofilho/pg-profiles"
    environment:
      - POSTGRES_PASSWORD=profiles
      - POSTGRES_USER=profiles
  backend:
    image: "robertofilho/profiles"
    environment:
      - DB_URL=jdbc:postgresql://db/profiles
    ports:
      - 8081:8081
    depends_on:
      - db